-- Selecionar a base de dados
USE felix_uber_shop;

-- Eliminar tabelas
DROP TABLE IF EXISTS ITEM_ENCOMENDA;
DROP TABLE IF EXISTS ENCOMENDA;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS PROMOCAO;
DROP TABLE IF EXISTS MOVIMENTO_CARTEIRA;
DROP TABLE IF EXISTS CARTEIRA;
DROP TABLE IF EXISTS UTILIZADOR;

-- Eliminar a base de dados
DROP DATABASE IF EXISTS felix_uber_shop;